server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.baker.learning.learntransaction.model

#mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    #druid version  1.0.20
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive:  20
    initialSize:  1
    maxWait:  6000
    minIdle: 5
    timeBetweenEvictionRunsMillis:  60000
    minEvictableIdleTimeMillis: 100000
    validationQuery:  select 1 from dual
    testWhileIdle:  true
    testOnBorrow: false
    testOnReturn:  false
    poolPreparedStatements: true
    maxOpenPreparedStatements:  20